steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-west1-docker.pkg.dev/projecto-microservicios/image-microservicios/products-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-west1-docker.pkg.dev/projecto-microservicios/image-microservicios/products-ms',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
